# Generated by Django 5.1.1 on 2024-10-07 19:03

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'project category',
                'verbose_name_plural': 'project categories',
                'db_table': 'project_category',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'product tag',
                'verbose_name_plural': 'product tags',
                'db_table': 'product_tag',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('birth_date', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Boshqa', 'Boshqa')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(choices=[('Toshkent', 'Toshkent'), ('Andijon', 'Andijon'), ('Samarqand', 'Samarqand'), ('Buxoro', 'Buxoro')], max_length=50)),
                ('city_or_district', models.CharField(choices=[('Toshkent shahar', 'Toshkent shahar'), ('Andijon shahar', 'Andijon shahar'), ('Samarqand shahar', 'Samarqand shahar')], max_length=50)),
                ('profile_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=90, scale=None, size=[100, 100], upload_to='profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('main_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[545, 621], upload_to='products/%Y/%m', verbose_name='1-Rasm')),
                ('main_image1', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[545, 621], upload_to='products/%Y/%m', verbose_name='2-Rasm')),
                ('main_image2', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[545, 621], upload_to='products/%Y/%m', verbose_name='3-Rasm')),
                ('main_image3', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=None, size=[545, 621], upload_to='products/%Y/%m', verbose_name='4-Rasm')),
                ('is_top', models.BooleanField(default=False, verbose_name='project is top')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='published date')),
                ('price', models.CharField(max_length=256, verbose_name='price')),
                ('brand', models.CharField(max_length=256, verbose_name='brand')),
                ('product_code', models.CharField(max_length=256, verbose_name='Product code')),
                ('product_count', models.IntegerField(default=0, verbose_name='product count')),
                ('categories', models.ManyToManyField(related_name='products', to='main.productcategory', verbose_name='categories')),
                ('tags', models.ManyToManyField(related_name='products', to='main.producttag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'product',
            },
        ),
    ]
