# Generated by Django 5.1.1 on 2024-10-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productcategory_producttag_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_code',
            new_name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Product_qount',
        ),
        migrations.AddField(
            model_name='product',
            name='product_count',
            field=models.IntegerField(default=0, verbose_name='product count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug'),
        ),
    ]
