# Generated by Django 5.1.1 on 2024-10-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_add_user_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='profiles/'),
            preserve_default=False,
        ),
    ]
